module.exports = {
  ENTRY_CREATED: "ENTRY_CREATED",
  ENTRY_FOUND: "ENTRY_FOUND",
  ENTRIES_RECEIVED: "ENTRIES_RECEIVED",
  ENTRY_DELETED: "ENTRY_DELETED",
  ENTRY_MODIFIED: "ENTRY_MODIFIED",
  EUCLIDIAN: "EUCLIDIAN",
  ENTRY_ERROR: "ENTRY_ERROR"
};
